format = """
[╭─](fg:current_line)\
$directory\
$fill\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue	= '#6272A4'
cyan = '#8BE9FD'
green	= '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red	= '#FF5555'
yellow = '#F1FA8C'

[directory]
format = '[─](fg:current_line)[](fg:pink)[󰷏 ](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~/"
truncation_symbol = ' '
truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[fill]
symbol = '─'
style = 'fg:current_line'

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[λ](fg:bold white)'
error_symbol = '[×](fg:bold red)'
